---
- name: Update apt cache (Debian)
  ansible.builtin.apt::
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install basic packages (Debian)
  ansible.builtin.apt:
    name: "{{ common_packages_debian }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Install basic packages (RHEL)
  ansible.builtin.yum:
    name: "{{ common_packages_rhel }}"
    state: present
  when: ansible_os_family == 'RedHat'
